version: '3.8'

services:
  api-gateway:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/nestdb
      JWT_SECRET: mysecretkey
    networks:
      - app-network

  client-web:
    build:
      context: ./apps/client/portal/web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodata:
